// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "bc3bd8241486e19b9a1b9f6344c053d046ffcd3d69707ad3627b7198ecc33d7c")
