// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "d0eee5e237f1013a38f1607d0122f1d158c350868cf411b9008f9740d862b819")
